FROM amazon/aws-cli

RUN yum install -y tar gzip curl && \
    curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-27.4.1.tgz -o docker.tgz && \
    tar -xzf docker.tgz && \
    mv docker/docker /usr/local/bin/ && \
    rm -rf docker docker.tgz && \
    yum install jq -y 